In [10]:
# importing numpy library
import numpy as np
from numpy import linalg as la

In [2]:
# create numpy 2d-array
m = np.array([[1, 2],[2, 3]])

print("Original square array:\n",m)

# finding eigenvalues and eigenvectors
w, v = np.linalg.eig(m)

# printing eigen values
print("Eigen values of the given square array:\n",w)

# printing eigen vectors
print("Eigenvectors of the given square array:\n",v)


Original square array:
 [[1 2]
 [2 3]]
Eigen values of the given square array:
 [-0.23606798  4.23606798]
Eigenvectors of the given square array:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [3]:
# create numpy 2d-array
m = np.array([[1, 2, 3],[2, 3, 4],[4, 5, 6]])

print("Original square array:\n",m)

# finding eigenvalues and eigenvectors
w, v = np.linalg.eig(m)

# printing eigen values
print("Eigen values of the given square array:\n",w)

# printing eigen vectors
print("Eigenvectors of the given square array:\n",v)


Original square array:
 [[1 2 3]
 [2 3 4]
 [4 5 6]]
Eigen values of the given square array:
 [ 1.08309519e+01 -8.30951895e-01 -3.58709921e-16]
Eigenvectors of the given square array:
 [[ 0.34416959  0.72770285  0.40824829]
 [ 0.49532111  0.27580256 -0.81649658]
 [ 0.79762415 -0.62799801  0.40824829]]


In [4]:
import numpy as np

# Prompt the user to enter the matrix dimensions (n x n)
n = int(input("Enter the size of the square matrix (n x n): "))

# Prompt the user to enter the matrix elements
print("Enter the matrix elements row by row:")

# Initialize an empty matrix
A = np.empty((n, n))

# Loop to input the matrix elements
for i in range(n):
    row = input(f"Enter values for row {i + 1} separated by spaces: ").split()
    A[i] = [float(x) for x in row]

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print the results
print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Enter the size of the square matrix (n x n): 2
Enter the matrix elements row by row:
Enter values for row 1 separated by spaces: 1 2
Enter values for row 2 separated by spaces: 1 2

Eigenvalues:
[0. 3.]

Eigenvectors:
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [5]:
# Create a numpy array
arr = np.array([[0, 0, 0], [2, 0, 0],[4, 0, 2], [3, 2, 0]],dtype=np.float32)

print("Original array:")
print(arr)

# Compute the factor by Singular Value
# Decomposition
U, s, V = np.linalg.svd(arr, full_matrices=False)

# Print the result
print("\nFactor of the given array by Singular Value Decomposition:")
print("\nU=", U, "\n\ns=", s, "\n\nV=", V)

Original array:
[[0. 0. 0.]
 [2. 0. 0.]
 [4. 0. 2.]
 [3. 2. 0.]]

Factor of the given array by Singular Value Decomposition:

U= [[ 4.6119910e-18  2.9790410e-17  1.0685136e-16]
 [-3.3100694e-01 -1.3877788e-16  9.4362831e-01]
 [-7.5490266e-01 -6.0000002e-01 -2.6480556e-01]
 [-5.6617701e-01  8.0000001e-01 -1.9860417e-01]] 

s= [5.701562  2.        0.7015621] 

V= [[-0.9436283  -0.19860417 -0.26480556]
 [-0.          0.8        -0.6       ]
 [ 0.33100694 -0.566177   -0.75490266]]


In [6]:
# Prompt the user to enter the matrix dimensions (m x n)
m = int(input("Enter the number of rows (m): "))
n = int(input("Enter the number of columns (n): "))

# Prompt the user to enter the matrix elements
print("Enter the matrix elements row by row separated by spaces:")
matrix_entries = []

# Loop to input the matrix elements
for i in range(m):
    row = input(f"Enter values for row {i + 1} separated by spaces: ").split()
    matrix_entries.append([float(x) for x in row])

# Create the matrix from user input
A = np.array(matrix_entries)

# Compute the SVD
U, S, VT = np.linalg.svd(A, full_matrices=False)

# Print the results
print("\nLeft Singular Vectors (U):")
print(U)

print("\nSingular Values (S):")
print(S)

print("\nRight Singular Vectors (VT):")
print(VT)

Enter the number of rows (m): 3
Enter the number of columns (n): 3
Enter the matrix elements row by row separated by spaces:
Enter values for row 1 separated by spaces: 1 2 3
Enter values for row 2 separated by spaces: 1 2 3
Enter values for row 3 separated by spaces: 1 2 3

Left Singular Vectors (U):
[[-0.57735027 -0.57735027 -0.57735027]
 [-0.57735027 -0.21132487  0.78867513]
 [-0.57735027  0.78867513 -0.21132487]]

Singular Values (S):
[6.4807407 0.        0.       ]

Right Singular Vectors (VT):
[[-0.26726124 -0.53452248 -0.80178373]
 [ 0.         -0.83205029  0.5547002 ]
 [ 0.96362411 -0.14824986 -0.22237479]]


In [8]:
matrix = []
x = int(input('Enter the size of the matrix:'))
for i in range(x):
    m = list(map(int,input(f"Enter the {i} row elements:").split()))
    if len(m) != x:
        print('Error')
    matrix.append(m)
print(matrix)
evalues, evectors = np.linalg.eig(matrix)
print("Eigen Values of the given matrix is:\n",evalues)
print("Eigen Vectorsof the given matrix is:\n",evectors)
print()
U,s,V = np.linalg.svd(matrix,full_matrices=False)
print("Factors of the given array by SVD :")
print("\nU = ",U,"\ns = ",s,"\nV = ",V)

Enter the size of the matrix:2
Enter the 0 row elements:1 2
Enter the 1 row elements:1 2
[[1, 2], [1, 2]]
Eigen Values of the given matrix is:
 [0. 3.]
Eigen Vectorsof the given matrix is:
 [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]

Factors of the given array by SVD :

U =  [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]] 
s =  [3.16227766 0.        ] 
V =  [[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]


In [11]:
la.svd(matrix)

(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([3.16227766, 0.        ]),
 array([[-0.4472136 , -0.89442719],
        [-0.89442719,  0.4472136 ]]))